name: non-sdk tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  non_sdk_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:

      - name: Check out GitHub repo
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipenv
        run: pip install -r requirements.txt

      - name: Set up for tests
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        shell: bash
        run: |
          make test-setup

      - name: Run tests
        shell: bash
        run: |
          make test

      - name: Coverage Summary
        run: |
          make coverage-summary
